In [1]:
import numpy as np
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("ex2data1.txt", header=None)
df.head()

0          1  2
0  34.623660  78.024693  0
1  30.286711  43.894998  0
2  35.847409  72.902198  0
3  60.182599  86.308552  1
4  79.032736  75.344376  1

In [36]:
X = df.iloc[:, :-1]
X.head()

0          1
0  34.623660  78.024693
1  30.286711  43.894998
2  35.847409  72.902198
3  60.182599  86.308552
4  79.032736  75.344376

In [37]:
y = df.iloc[:,-1]
y.head()

0    0
1    0
2    0
3    1
4    1
Name: 2, dtype: int64

In [38]:
X = np.c_[np.ones((X.shape[0], 1)), X]
X

array([[ 1.        , 34.62365962, 78.02469282],
       [ 1.        , 30.28671077, 43.89499752],
       [ 1.        , 35.84740877, 72.90219803],
       [ 1.        , 60.18259939, 86.3085521 ],
       [ 1.        , 79.03273605, 75.34437644],
       [ 1.        , 45.08327748, 56.31637178],
       [ 1.        , 61.10666454, 96.51142588],
       [ 1.        , 75.02474557, 46.55401354],
       [ 1.        , 76.0987867 , 87.42056972],
       [ 1.        , 84.43281996, 43.53339331],
       [ 1.        , 95.86155507, 38.22527806],
       [ 1.        , 75.01365839, 30.60326323],
       [ 1.        , 82.30705337, 76.4819633 ],
       [ 1.        , 69.36458876, 97.71869196],
       [ 1.        , 39.53833914, 76.03681085],
       [ 1.        , 53.97105215, 89.20735014],
       [ 1.        , 69.07014406, 52.74046973],
       [ 1.        , 67.94685548, 46.67857411],
       [ 1.        , 70.66150955, 92.92713789],
       [ 1.        , 76.97878373, 47.57596365],
       [ 1.        , 67.37202755, 42.838

In [41]:
y = y[:,np.newaxis]
y

array([[0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
    

In [59]:
theta = np.zeros((X.shape[1], 1))
theta

array([[0.],
       [0.],
       [0.]])

In [57]:
def hypothesis(theta, X):
    z = np.dot(X, theta)
    return 1/(1+np.exp(-(z))) - 0.0000001

In [77]:
h = hypothesis(theta, X)
np.dot(X.T, (h-y))

array([[  -10.00001   ],
       [-1200.92231537],
       [-1126.28488277]])

In [58]:
def costFunc(theta, X , y):
    y1 = hypothesis(theta, X)
    m = X.shape[0]
    return -(1/m) * np.sum(y*np.log(y1) + (1-y)*np.log(1-y1))

In [63]:
def gradient(theta, X, y):
    m = X.shape[0]
    h = hypothesis(theta, X)
    return 1/m * np.dot(X.T, (h-y))

In [64]:
from scipy.optimize import minimize, fmin_tnc
def fit(X,y,theta):
    para = fmin_tnc(func=costFunc, x0=theta, fprime=gradient, args=(X, y.flatten()))
    return para[0]
parameters = fit(X, y , theta)

In [65]:
parameters

array([-25.16133919,   0.20623176,   0.20147167])

In [69]:
h = hypothesis(parameters, X)
h

array([9.10338180e-02, 4.21586616e-05, 4.39087543e-02, 9.90424653e-01,
       9.98198663e-01, 1.07974271e-02, 9.98978046e-01, 4.23227221e-01,
       9.99709922e-01, 7.35388275e-01, 9.09674555e-01, 2.85966215e-02,
       9.99270048e-01, 9.99853846e-01, 1.56037031e-01, 9.80959344e-01,
       4.27717091e-01, 1.48789120e-01, 9.99706445e-01, 5.74281053e-01,
       6.68348801e-02, 9.98627154e-01, 7.41791028e-03, 1.01054741e-04,
       9.91878194e-01, 8.55048927e-01, 6.00299020e-01, 8.65185055e-01,
       9.23891643e-02, 1.68287908e-02, 8.97130992e-01, 9.81037336e-01,
       1.54910944e-01, 3.91938827e-01, 7.41288671e-02, 3.31106407e-02,
       8.52268325e-01, 9.87564277e-01, 2.03987704e-01, 4.95798448e-02,
       9.70300397e-01, 6.11812100e-03, 9.99461389e-01, 5.02285337e-01,
       4.48859197e-03, 1.37023749e-01, 9.92991743e-01, 9.99996081e-01,
       9.99204822e-01, 9.99990661e-01, 9.98106695e-01, 9.99500391e-01,
       9.05016084e-01, 2.80603859e-03, 8.52260039e-03, 5.28908465e-02,
      

In [70]:
def predict(h):
    h1 = []
    for i in h:
        if i>=0.5:
            h1.append(1)
        else:
            h1.append(0)
    return h1
y_pred = predict(h)
accuracy = 0
for i in range(0, len(y_pred)):
    if y_pred[i] == y[i]:
        accuracy += 1
accuracy/len(y)

0.89